services:
  - type: web
    name: boardly-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    disk:
      name: sqlite-data
      mountPath: /var/data
      sizeGB: 1